{
    "name": "Project Notebook",
    "version": "1.0.0",
    "summary": "Project notebooks with data sources and run history",
    "description": """Interactive notebooks with multi-database data sources and scheduling, integrated under Project.""",
    "category": "Project/Notebook",
    "author": "In-house",
    "license": "LGPL-3",
    "website": "https://www.zphile.com",
    "depends": ["base", "mail", "web", "project", "document_page_project"],
    "data": [
        "security/devops_security.xml",
        "security/devops_training_security.xml",
        "security/devops_schedule_security.xml",
        "security/ir.model.access.csv",
        "data/no_datasource.xml",
        "views/devops_notebook_views.xml",
        "views/devops_data_source_views.xml",
        "views/devops_requirement_views.xml",
        "views/devops_issue_views.xml",
        "views/res_config_settings_views.xml",
        "views/devops_mail_views.xml",
        "views/devops_training_views.xml",
        "views/notebook_transfer_views.xml",
        "views/devops_menu.xml",
        "data/devops_notebook_cron.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "project_notebook/static/src/scss/notebook.scss",
            "project_notebook/static/src/js/execution_mode_widget.js",
            "project_notebook/static/src/js/notebook_modal_resize.js",
            "project_notebook/static/src/js/view_type_alias.js",
            "project_notebook/static/src/js/error_dialog_clipboard_safe.js",
            "project_notebook/static/src/js/notebook_toggle_inputs.js",
        ],
    },
    "post_init_hook": "post_init_hook",
    "application": True,
    "auto_install": False,
}
